### ISSUE TITLE
Important Issue

### ISSUE THREAD

**Issue by ValiantWind** [Biack1st/Rogold-features-for-free#1]
Imagine stealing an extension what a loser 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮

**Comment by Biack1st** [comment]
> Imagine stealing an extension what a loser 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮

agreed

**Comment by commitblue** [comment]
bro spams issues at a repo

**Comment by ValiantWind** [comment]
@commitblue 
This issue is over 6 months old

Closing it now.
