### ISSUE TITLE
Delete this repository and your life

### ISSUE THREAD

**Issue by ValiantWind** [Biack1st/Rogold-features-for-free#2]
Imagine stealing an extension what a loser 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮

**Comment by ExperiencersInternational** [comment]
imagine giving someone a version of the plugin that made all features free @ValiantWind69

**Comment by Biack1st** [comment]
> imagine giving someone a version of the plugin that made all features free @ValiantWind69

agreed, very bad thing to do. I will now delete my life.

**Comment by ValiantWind** [comment]
@ExperiencersInternational Biack1st didn't get this from me dumbo.

**Comment by ExperiencersInternational** [comment]
I know @ValiantWind69, you gave me a copy that made all features free though

**Comment by ValiantWind** [comment]
@ExperiencersInternational 

You decided to take it

**Comment by ExperiencersInternational** [comment]
@ValiantWind really nice randomly closing it

I wonder whether @Biack1st would do the Ultimate version

**Comment by ValiantWind** [comment]
> @ValiantWind really nice randomly closing it
> 
> I wonder whether @Biack1st would do the Ultimate version

I wanted to clean my github issue list. This isn't relevant anymore.

 Free ultimate isn't possible btw, due to all the features being locked behind a private API which we can't modify.

**Comment by ExperiencersInternational** [comment]
I swear did GitHub reactions go?

either way, that's a shame but it's needed
